### ISSUE TITLE
Unable to push separate testcases from Scenario Outline using spec sync

### ISSUE THREAD

**Issue by soubhonik** [specsolutions/specsync-for-tfs-documentation#2]
Hi ,

Can we push each example as a separate testcase using Scenario Outline instead of each record going as parameter ?

Thanks

**Comment by gasparnagy** [comment]
Currently not. In Gherkin you cannot tag a particular example, so associating a different Test Case ID for each example would not be possible with tags. Please send an email to support@specsolutions.eu, so that we can better discuss alternatives for your requirement.
