### ISSUE TITLE
Azure DevOps Authentication misses the System.AccessToken option

### ISSUE THREAD

**Issue by dnperfors** [specsolutions/specsync-for-tfs-documentation#4]
When debugging an authentication issue, I stumbled across the [tfs authentication options](https://github.com/specsolutions/specsync-for-tfs-documentation/blob/master/features/general-features/tfs-authentication-options.md) page and noticed that the `$(System.AccessToken)` option is not mentioned.
The way to get `$(System.AccessToken)` working is by granting the "Build Administrators" group the rights to "Manage Test Suites" in the "Area" section.

**Comment by gasparnagy** [comment]
Thank you @dnperfors for the suggestion. I have updated the documentation accordingly.
