### ISSUE TITLE
Don't suggest Full Access for PAT token

### ISSUE THREAD

**Issue by dnperfors** [specsolutions/specsync-for-tfs-documentation#5]
In [Personal access token](https://github.com/specsolutions/specsync-for-tfs-documentation/blob/master/features/general-features/tfs-authentication-options.md#personal-access-tokens--) it is suggested to give the PAT token "Full Access". Since this is a bad practice, I tried to minimalize the rights for the token and are left with the following rights:

- Test management (Read & Write)
- Work items (Read)

Could you mention that in the documentation?

**Comment by gasparnagy** [comment]
@dnperfors this issue have been overseen, but the documentation contains the necessary permissions since then, so I close this.
