### ISSUE TITLE
Do not provide a use case for using SYSTEM_PULLREQUEST_PULLREQUESTID

### ISSUE THREAD

**Issue by wafec** [specsolutions/specsync-for-tfs-documentation#6]
Took me a while to understand a use case where I might use the SYSTEM_PULLREQUEST_PULLREQUESTID with SpecSync in this [page](https://github.com/specsolutions/specsync-for-tfs-documentation/blob/master/features/push-features/customization-automatically-link-changed-test-cases.md).

Should be interesting to provide at least in simple words where this is possible. Currently, my team uses it triggered by any change that comes into the master branch then creating or updating the test cases. But, in this time, seems the SYSTEM_PULLREQUEST_PULLREQUESTID is not there anymore and can't be retrieved at least we parse it from the Git message that comes with the squash operation (e.g. Merged PR 12345: lorem...).

Seems not feasible to use SpecSync in the Pull Request context as the changes are still happening. So, in my point of view, the only place between the Pull Request branch build and the master branch build is after completing the PR but yet in the context of the PR. If the part of the documentation that is saying that it is possible to use this environment variable from the pipeline (like as in the example provided) so I think this is worth mentioning in the documentation because so far we are doing some workarounds to provide the Pull Request number when running by trigger on the master branch.

**Comment by gasparnagy** [comment]
Thank you @wafec for the useful comment. It makes absolute sense. I have added a note to the documentation page to clarify the case.
